---
title: "20180827_同盾决策树"
author: "hu"
date: "2018年8月27日"
output: html_document
---
# 基于同盾数据的决策树（淘系）
 参考链接（假的）：<http://rmarkdown.rstudio.com>.
```{r include=FALSE}
#调包
library(dplyr)
```

## 载入数据
```{r setup}
traindata=read.csv('D:\\python\\data\\20180825_tongdun.csv')
dim(traindata) 
```

## 数据整理
### dplyr:：%>%管道操作命令

```{r %>% }
##管道操作
dat<-traindata%>%filter(flag_loan==1)%>%filter(month_decision=='2017-12'|month_decision=='2018-01'|month_decision=='2018-02'|month_decision=='2018-03')%>%filter(max_platform=='TAOBAO'|max_platform=='TMALL')%>%select(score_tongdun,X6m_phone_plt,X3m_idcard_plt,X6m_idcard_p2p,X1m_phone_plt,X6m_phone_p2p,X3m_idcard_p2p,revolving_type_apply,RF_score_v4,cut_alipay_order,age,rf_score,gmv12,MobDr1to4_od30)
summary(dat)
```
将数据分为训练集和测试集，注意set.seed保持随机种子稳定
```{r}
#设置随机分配2#
smp_size <- floor(0.6 * nrow(dat))
set.seed(2)
train_ind <- sample(seq_len(nrow(dat)), size = smp_size)
train <- dat[train_ind, ]
test <- dat[-train_ind, ]
dim(train)
dim(test)
```
利用train集建模并画出决策树
```{r}
#rpart#
library(rpart)
fit<-(MobDr1to4_od30~.)
rtree<-rpart(fit,minsplit=10, cp=0.02,maxdepth=4,data=train)
printcp(rtree)

library(rpart.plot) #调出rpart.plot包
rpart.plot(rtree, type=2) 
```

### 描述规则如下：
规则1 6m_phone_plt<14 and rf_score>=20 and score_tongdun>=0.9 p=0.0098
规则2 6m_phone_plt<14 and rf_score>=20 and score_tongdun<0.9 p=0.035
规则3 6m_phone_plt<14 and rf_score<20 p=0.11
规则4 6m_phone_plt>=14 and gmv12>=17000 p=0.12
规则5 6m_phone_plt>=14 and gmv12<17000 and 3m_idcard_plt>=18 p=0.22
规则6 6m_phone_plt>=14 and gmv12<17000 and 3m_idcard_plt<18 p=1

检验决策树在实验集和测试集的效果是否相差巨大：
```{r}
#检验预测效果#
pre_train<-predict(rtree)
table(pre_train,train$MobDr1to4_od30)

#检验test集预测效果#
pre_test<-predict(rtree, newdata = test)
table(pre_test, test$MobDr1to4_od30)
```
画train集的roc曲线，并计算AUC的值
```{r}
library(pROC)
## train
modelroc <- roc(train$MobDr1to4_od30,pre_train)
plot(modelroc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)

```
画test集的roc曲线，并计算AUC的值
```{r}
## test
modelroc <- roc(test$MobDr1to4_od30,pre_test)
plot(modelroc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)
```


### 随机打乱重新分配样本到test，检验AUC是否一致：
第一次实验：
```{r,echo=FALSE}
#随机检验  test的效果
smp_size <- floor(0.6 * nrow(dat))
set.seed(23)
train_ind <- sample(seq_len(nrow(dat)), size = smp_size)
#train <- dat[train_ind, ]
test <- dat[-train_ind, ]
#dim(train)
#dim(test)


#检验test集预测效果#
pre_test<-predict(rtree, newdata = test)
table(pre_test, test$MobDr1to4_od30)

library(pROC)
## test
modelroc <- roc(test$MobDr1to4_od30,pre_test)
plot(modelroc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)



```

第二次实验：
```{r,echo=FALSE}
#随机检验  test的效果
smp_size <- floor(0.6 * nrow(dat))
set.seed(5434)
train_ind <- sample(seq_len(nrow(dat)), size = smp_size)
#train <- dat[train_ind, ]
test <- dat[-train_ind, ]
#dim(train)
#dim(test)


#检验test集预测效果#
pre_test<-predict(rtree, newdata = test)
table(pre_test, test$MobDr1to4_od30)

library(pROC)
## test
modelroc <- roc(test$MobDr1to4_od30,pre_test)
plot(modelroc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)



```


















